### ISSUE TITLE
(feature) Fetch all the open issues from this repo

### ISSUE THREAD

**Issue by aayushmau5** [JIITODC/bot#18]
**Describe the feature you want to propose**
A `/issue` command which get all the open issues from this repo.

**Implementation**
All the open issues can be fetched from https://api.github.com/repos/JIITODC/bot/issues

**Additional context**
Mockup:
![image](https://user-images.githubusercontent.com/54525741/99790434-1b44cc80-2b4a-11eb-842d-d5c00da7887f.png)

**Comment by Onyx2406** [comment]
working..

**Comment by aayushmau5** [comment]
Close by https://github.com/JIITODC/bot/pull/25
