### ISSUE TITLE
(bug) bot commands don't show up correctly in the help message

### ISSUE THREAD

**Issue by DelusionalOptimist** [JIITODC/bot#20]
## Describe the bug
Possibly the commands are being rendered as markdown and thus the `_` (underscore) in the bot username makes text italic. 

## To Reproduce
Send the bot `/help@bot_name` and it will reply you with the broken help message.

## Expected behavior
The commands in the message should look like `/xkcd@bot_name`, `/links@bot_name` .... 

## Screenshots
![jodc_bot_broken_help_msg](https://user-images.githubusercontent.com/54525605/105490371-ae30ed00-5cda-11eb-941b-a50f058bb242.png)
**Notice how the commands look like _/command@botname_**

## Platform
 OS agnostic

## Additional context
If its your first time contributing to the project, welcome :hugs: . Take a look at the [contributing guide](https://github.com/JIITODC/bot/blob/master/CONTRIBUTING.md) which is a step by step guide on getting the bot setup. 
We use the `python-telegram-bot` API wrapper. Here is a link to its documentation: https://python-telegram-bot.readthedocs.io/en/stable/index.html .
Do comment below something like 'I want to work on this issue' to let others know that you're working on this. Feel free to ask about any doubts you have or problems you're facing.

**Comment by sarthakpant772** [comment]
can i work on this?

**Comment by DelusionalOptimist** [comment]
Sure @sarthakpant772. : )
But just to make sure @Onyx2406, you aren't handling this in https://github.com/JIITODC/bot/pull/23 , right?

**Comment by Onyx2406** [comment]
> Sure @sarthakpant772. : )
> But just to make sure @Onyx2406, you aren't handling this in #23 , right?

Yes I am not working on this one.

**Comment by DelusionalOptimist** [comment]
All yours @sarthakpant772 :raised_hands:

**Comment by sarthakpant772** [comment]
Hey, i m just little confused that what should be correct output it should give? sry for the disturbance.

**Comment by sarthakpant772** [comment]
I made prasemode.markdown to prasemode.html and here is the result. 
![image](https://user-images.githubusercontent.com/67951999/131349944-d6d55e3e-2175-43f3-8d4c-cb3bab13babb.png)

**Comment by aayushmau5** [comment]
Yup, that looks like the expected output.

**Comment by sarthakpant772** [comment]
Should i open a pr or shoud i wait for @DelusionalOptimist sir to check this?

**Comment by aayushmau5** [comment]
Open a PR. If we find any issues, we will comment on the issue itself :)
